name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 mypy pytest
    - name: Lint with flake8
      run: |
        flake8 python
    - name: Type check with mypy
      run: |
        mypy python
    - name: Run tests with pytest
      run: |
        pytest python
